-- General Settings
require('plugins')
require('settings')
require('keymappings')
require('colorscheme')

-- Plugins
require('p-compe')
require('p-nvimtree')
require('p-barbar')
require('p-lualine')
require('p-lsp_extensions')
require('p-telescope')
require('p-treesitter')
require('p-formatter')
require('p-vim_rooter')
require('p-colorizer')
require('p-lspkind')
require('p-floaterm')
require('p-dashboard')
require('p-indent')
require('p-markdown')
require('p-kommentary')
require('p-hop')
require('p-neoscroll')
require('p-dap')
require('p-rest_nvim')

-- LSP
require('lsp')
require('p-lspinstall')
