# ~/.config/himalaya/config.toml

name = "Antonio Bennett"
downloads-dir = "~/Downloads"
signature = """
--
Best Regards,
Antonio
"""

[gmail]
default = true
email = "bennettantonio199@gmail.com"

imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "bennettantonio199@gmail.com"
imap-passwd-cmd = "echo !1932Seneca!!!"

smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "bennettantonio199@gmail.com"
smtp-passwd-cmd = "security find-internet-password -gs gmail -w"
